In [ ]:
#testing colab notebook
print("Hey google")

Hey google


In [ ]:
#checking out basics
a = 40
b = 30
print(a,b)

40 30


In [ ]:
#playing with numpy as they are faster than lists
import numpy as np
a = np.array([4,6,3,1,5]) #converts list into np arrays
print(np.max(a))
print(np.min(a))

6
1


In [ ]:
import numpy as np
a = np.arange(9.).reshape(3,3)
print(a)
a = a*2
print(a)
a[a>=6] = 50.
print(a)
print(a[0,1])
print(a[:,1]) #slicing
print("Sum is {}".format(np.sum(a, axis=0))) #axis=0 for column, axis=1 for row

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[[ 0.  2.  4.]
 [ 6.  8. 10.]
 [12. 14. 16.]]
[[ 0.  2.  4.]
 [50. 50. 50.]
 [50. 50. 50.]]
2.0
[ 2. 50. 50.]
Sum is [100. 102. 104.]


In [ ]:
#pandas
import pandas as pd

ser = pd.Series([5,6,7,8])
print(ser)
print(ser.values)

#dataframes of pandas for data handling
scottish_hills = {'Hill Name': ['Ben Nevis', 'Ben Macdui', 'Braeriach', 'Cairn Toul', 'Sgòr an Lochain Uaine'],
                  'Height': [1345, 1309, 1296, 1291, 1258],
                  'Latitude': [56.79685, 57.070453, 57.078628, 57.054611, 57.057999],
                  'Longitude': [-5.003508, -3.668262, -3.728024, -3.71042, -3.725416]}

df = pd.DataFrame(scottish_hills) #each column is a series containing values of same data type
print(df,"\n")
print(df.head(3),"\n") #first three rows
print(df["Latitude"],"\n") #access a series(column)
#use iloc for particular [row,col] access
print(df.iloc[1,0],"\n")
#u can treat columnn names as attribute
df.Height > 1300

0    5
1    6
2    7
3    8
dtype: int64
[5 6 7 8]
               Hill Name  Height   Latitude  Longitude
0              Ben Nevis    1345  56.796850  -5.003508
1             Ben Macdui    1309  57.070453  -3.668262
2              Braeriach    1296  57.078628  -3.728024
3             Cairn Toul    1291  57.054611  -3.710420
4  Sgòr an Lochain Uaine    1258  57.057999  -3.725416 

    Hill Name  Height   Latitude  Longitude
0   Ben Nevis    1345  56.796850  -5.003508
1  Ben Macdui    1309  57.070453  -3.668262
2   Braeriach    1296  57.078628  -3.728024 

0    56.796850
1    57.070453
2    57.078628
3    57.054611
4    57.057999
Name: Latitude, dtype: float64 

Ben Macdui 



0     True
1     True
2    False
3    False
4    False
Name: Height, dtype: bool